# Generated by Django 5.2.4 on 2025-08-07 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnownPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('shivir', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='known_faces/')),
                ('encoding', models.BinaryField(blank=True, null=True)),
                ('is_blacklisted', models.BooleanField(default=False, help_text='If checked, attendance will not be marked for this person')),
                ('blacklisted_reason', models.CharField(blank=True, help_text='Reason for blacklisting', max_length=200, null=True)),
                ('blacklisted_date', models.DateTimeField(blank=True, help_text='Date when person was blacklisted', null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Designates whether this user is active. Inactive users won't appear in face recognition.")),
                ('deactivated_date', models.DateTimeField(blank=True, help_text='Date when person was deactivated', null=True)),
                ('deactivated_reason', models.CharField(blank=True, help_text='Reason for deactivation', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.CharField(blank=True, max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.knownperson')),
            ],
        ),
    ]
