# Generated by Django 5.2.4 on 2025-08-07 06:13

import faceapp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_alter_knownperson_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownperson',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=faceapp.storage.OverwriteStorage(), upload_to='known_faces/'),
        ),
    ]
