# Generated by Django 5.2.4 on 2025-08-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0003_alter_knownperson_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-timestamp']},
        ),
    ]
