# Generated by Django 5.2.4 on 2025-08-07 09:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0004_alter_attendance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TejgyanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(help_text="e.g., 'Morning MA Shivir', 'Evening SSP1', 'Diwali Festival Session'", max_length=100)),
                ('session_type', models.CharField(choices=[('MA', 'MA Shivir (Entry Level)'), ('SSP1', 'SSP1 (MTS 1)'), ('SSP2', 'SSP2 (MTS 2)'), ('HS1', 'Higher Shivir 1'), ('HS2', 'Higher Shivir 2'), ('FESTIVAL', 'Festival/Open Session')], help_text='Select the type of session conducted by Sirshree', max_length=20)),
                ('session_date', models.DateField(default=django.utils.timezone.now, help_text='Date when this session is/was conducted')),
                ('conducted_by', models.CharField(default='Sirshree', help_text='Name of the person conducting the session', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text="Check this to make it today's active session for face recognition attendance marking. Only ONE session can be active at a time.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tejgyan Session',
                'verbose_name_plural': 'Tejgyan Sessions',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by_system',
            field=models.BooleanField(default=True, help_text='True if marked by face recognition, False if manually added'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The specific Tejgyan session this attendance is for', null=True, on_delete=django.db.models.deletion.CASCADE, to='faceapp.tejgyansession'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('person', 'session'), name='unique_person_session_daily_attendance'),
        ),
    ]
