# Generated by Django 5.2.4 on 2025-08-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0005_tejgyansession_attendance_marked_by_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Session will be NULL until admin selects an active session', null=True, on_delete=django.db.models.deletion.CASCADE, to='faceapp.tejgyansession'),
        ),
    ]
