# Generated by Django 5.2.4 on 2025-08-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0006_alter_attendance_session'),
    ]

    operations = [
    ]
