# Generated by Django 5.2.4 on 2025-08-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0007_auto_20250807_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tejgyansession',
            name='session_type',
            field=models.CharField(choices=[('MA', 'MA Shivir (Entry Level)'), ('SSP1', 'SSP1 (MTS 1)'), ('SSP2', 'SSP2 (MTS 2)'), ('HS1', 'Higher Shivir 1'), ('HS2', 'Higher Shivir 2'), ('FESTIVAL', 'Festival/Open Session')], help_text='Select the type of session conducted by Tejgyan Foundation', max_length=20),
        ),
    ]
