# Generated by Django 5.2.4 on 2025-08-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0010_alter_tejgyansession_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('MA', 'MA Shivir'), ('SSP1', 'SSP1'), ('SSP2', 'SSP2'), ('HS1', 'Higher Shivir 1'), ('HS2', 'Higher Shivir 2'), ('FESTIVAL', 'Festival/Open Session')], max_length=20)),
                ('previous_attendance_date', models.DateField(help_text='When they last attended this session type')),
                ('repeat_start_date', models.DateField(auto_now_add=True, help_text="Today's repeat attendance")),
                ('days_gap', models.IntegerField(help_text='Dynamic calculation of days between visits')),
                ('repeat_count', models.IntegerField(default=1, help_text='1st repeat, 2nd repeat, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_attendance', to='faceapp.knownperson')),
            ],
            options={
                'verbose_name': 'Repeat Session Attendance',
                'verbose_name_plural': 'Repeat Session Attendances',
                'ordering': ['-repeat_start_date'],
                'indexes': [models.Index(fields=['session_type', 'person'], name='faceapp_rep_session_441486_idx'), models.Index(fields=['session_type', 'repeat_start_date'], name='faceapp_rep_session_ae7990_idx'), models.Index(fields=['person', 'session_type', 'repeat_count'], name='faceapp_rep_person__3f6155_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('MA', 'MA Shivir'), ('SSP1', 'SSP1'), ('SSP2', 'SSP2'), ('HS1', 'Higher Shivir 1'), ('HS2', 'Higher Shivir 2'), ('FESTIVAL', 'Festival/Open Session')], max_length=20)),
                ('session_start_date', models.DateField()),
                ('days_attended', models.IntegerField(default=0)),
                ('days_required', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_progress', to='faceapp.knownperson')),
            ],
            options={
                'verbose_name': 'Session Progress',
                'verbose_name_plural': 'Session Progress Records',
                'ordering': ['-session_start_date'],
                'indexes': [models.Index(fields=['session_type', 'person'], name='faceapp_ses_session_8d7c34_idx'), models.Index(fields=['session_type', 'is_completed'], name='faceapp_ses_session_dac9d8_idx'), models.Index(fields=['person', 'session_type', 'is_completed'], name='faceapp_ses_person__632502_idx')],
                'unique_together': {('person', 'session_type', 'session_start_date')},
            },
        ),
    ]
