# Generated by Django 5.2.4 on 2025-08-14 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0012_alter_sessionprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hs1_repeaters',
            name='day_number',
            field=models.PositiveIntegerField(default=1, help_text='Day 1 or 2 of HS1 repeat'),
        ),
        migrations.AddField(
            model_name='hs1_repeaters',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='True when both repeat days completed'),
        ),
        migrations.AddField(
            model_name='hs1_repeaters',
            name='session_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faceapp.tejgyansession'),
        ),
        migrations.AddField(
            model_name='hs2_repeaters',
            name='day_number',
            field=models.PositiveIntegerField(default=1, help_text='Day 1 or 2 of HS2 repeat'),
        ),
        migrations.AddField(
            model_name='hs2_repeaters',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='True when both repeat days completed'),
        ),
        migrations.AddField(
            model_name='hs2_repeaters',
            name='session_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faceapp.tejgyansession'),
        ),
        migrations.AddField(
            model_name='ma_repeaters',
            name='day_number',
            field=models.PositiveIntegerField(default=1, help_text='Day progression: 1, 2, 3, 4, or 5 for MA repeat'),
        ),
        migrations.AddField(
            model_name='ma_repeaters',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='True when all 5 repeat days completed'),
        ),
        migrations.AddField(
            model_name='ma_repeaters',
            name='session_reference',
            field=models.ForeignKey(blank=True, help_text='Link to specific session for this repeat', null=True, on_delete=django.db.models.deletion.CASCADE, to='faceapp.tejgyansession'),
        ),
        migrations.AddField(
            model_name='ssp1_repeaters',
            name='day_number',
            field=models.PositiveIntegerField(default=1, help_text='Day 1 or 2 of SSP1 repeat'),
        ),
        migrations.AddField(
            model_name='ssp1_repeaters',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='True when both repeat days completed'),
        ),
        migrations.AddField(
            model_name='ssp1_repeaters',
            name='session_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faceapp.tejgyansession'),
        ),
        migrations.AddField(
            model_name='ssp2_repeaters',
            name='day_number',
            field=models.PositiveIntegerField(default=1, help_text='Day 1 or 2 of SSP2 repeat'),
        ),
        migrations.AddField(
            model_name='ssp2_repeaters',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='True when both repeat days completed'),
        ),
        migrations.AddField(
            model_name='ssp2_repeaters',
            name='session_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faceapp.tejgyansession'),
        ),
        migrations.AlterUniqueTogether(
            name='hs1_repeaters',
            unique_together={('person', 'session_reference')},
        ),
        migrations.AlterUniqueTogether(
            name='hs2_repeaters',
            unique_together={('person', 'session_reference')},
        ),
        migrations.AlterUniqueTogether(
            name='ma_repeaters',
            unique_together={('person', 'session_reference')},
        ),
        migrations.AlterUniqueTogether(
            name='ssp1_repeaters',
            unique_together={('person', 'session_reference')},
        ),
        migrations.AlterUniqueTogether(
            name='ssp2_repeaters',
            unique_together={('person', 'session_reference')},
        ),
        migrations.AddIndex(
            model_name='ma_repeaters',
            index=models.Index(fields=['person', 'day_number'], name='faceapp_ma__person__d1feb8_idx'),
        ),
    ]
