# Generated by Django 5.2.4 on 2025-08-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0013_hs1_repeaters_day_number_hs1_repeaters_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ma_repeaters',
            name='faceapp_ma__person__d1feb8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='hs1_repeaters',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hs2_repeaters',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ma_repeaters',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ssp1_repeaters',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ssp2_repeaters',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hs1_repeaters',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='hs1_repeaters',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='hs1_repeaters',
            name='session_reference',
        ),
        migrations.RemoveField(
            model_name='hs2_repeaters',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='hs2_repeaters',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='hs2_repeaters',
            name='session_reference',
        ),
        migrations.RemoveField(
            model_name='ma_repeaters',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='ma_repeaters',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='ma_repeaters',
            name='session_reference',
        ),
        migrations.RemoveField(
            model_name='ssp1_repeaters',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='ssp1_repeaters',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='ssp1_repeaters',
            name='session_reference',
        ),
        migrations.RemoveField(
            model_name='ssp2_repeaters',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='ssp2_repeaters',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='ssp2_repeaters',
            name='session_reference',
        ),
    ]
