# Generated by Django 5.2.4 on 2025-08-14 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0014_remove_ma_repeaters_faceapp_ma__person__d1feb8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hs1_repeaters',
            name='day_number',
            field=models.IntegerField(default=1, help_text='Day 1 or 2 of HS1 repeat'),
        ),
        migrations.AddField(
            model_name='hs1_repeaters',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='True when repeat session completed'),
        ),
        migrations.AddField(
            model_name='hs1_repeaters',
            name='session_reference',
            field=models.ForeignKey(blank=True, help_text='Reference to the active session', null=True, on_delete=django.db.models.deletion.CASCADE, to='faceapp.tejgyansession'),
        ),
        migrations.AddField(
            model_name='hs2_repeaters',
            name='day_number',
            field=models.IntegerField(default=1, help_text='Day 1 or 2 of HS2 repeat'),
        ),
        migrations.AddField(
            model_name='hs2_repeaters',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='True when repeat session completed'),
        ),
        migrations.AddField(
            model_name='hs2_repeaters',
            name='session_reference',
            field=models.ForeignKey(blank=True, help_text='Reference to the active session', null=True, on_delete=django.db.models.deletion.CASCADE, to='faceapp.tejgyansession'),
        ),
        migrations.AddField(
            model_name='ma_repeaters',
            name='day_number',
            field=models.IntegerField(default=1, help_text='Day 1, 2, 3, 4, or 5 of MA repeat'),
        ),
        migrations.AddField(
            model_name='ma_repeaters',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='True when repeat session completed'),
        ),
        migrations.AddField(
            model_name='ma_repeaters',
            name='session_reference',
            field=models.ForeignKey(blank=True, help_text='Reference to the active session', null=True, on_delete=django.db.models.deletion.CASCADE, to='faceapp.tejgyansession'),
        ),
        migrations.AddField(
            model_name='ssp1_repeaters',
            name='day_number',
            field=models.IntegerField(default=1, help_text='Day 1 or 2 of SSP1 repeat'),
        ),
        migrations.AddField(
            model_name='ssp1_repeaters',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='True when repeat session completed'),
        ),
        migrations.AddField(
            model_name='ssp1_repeaters',
            name='session_reference',
            field=models.ForeignKey(blank=True, help_text='Reference to the active session', null=True, on_delete=django.db.models.deletion.CASCADE, to='faceapp.tejgyansession'),
        ),
        migrations.AddField(
            model_name='ssp2_repeaters',
            name='day_number',
            field=models.IntegerField(default=1, help_text='Day 1 or 2 of SSP2 repeat'),
        ),
        migrations.AddField(
            model_name='ssp2_repeaters',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='True when repeat session completed'),
        ),
        migrations.AddField(
            model_name='ssp2_repeaters',
            name='session_reference',
            field=models.ForeignKey(blank=True, help_text='Reference to the active session', null=True, on_delete=django.db.models.deletion.CASCADE, to='faceapp.tejgyansession'),
        ),
    ]
